[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

# Tokyo Night theme
# ref: https://github.com/zatchheems/tokyo-night-alacritty-theme?tab=readme-ov-file

[colors]

  [colors.primary]
    background = '#1a1b26'
    foreground = '#a9b1d6'

  # Cursor colors
  # These will only be used when `custom_cursor_colors=true` 
  [colors.cursor]
    text = '#ecf2f8'
    cursor = '#c6cdd5'

  # Normal colors
  [colors.normal]
    black = '#32344a'
    red = '#f7768e'
    green = '#9ece6a'
    yellow = '#e0af68'
    blue = '#7aa2f7'
    magenta = '#ad8ee6'
    cyan = '#449dab'
    white = '#787c99'

  # Bright colors
  [colors.bright]
    black = '#444b6a'
    red = '#ff7a93'
    green = '#b9f27c'
    yellow = '#ff9e64'
    blue = '#7da6ff'
    magenta = '#bb9af7'
    cyan = '#0db9d7'
    white = '#acb0d0'

[env]
	term = "xterm-256color"

# Cursor settings
# [cursor]
# blink_interval = 750
# [cursor.style]
# shape = "Beam"
# blinking = "Always"
